name: Postman Tests

on:
  workflow_call:
    secrets:
      SecretKey:
        required: true

jobs:
  run-postman:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
         POSTGRES_PASSWORD: Password123!
         POSTGRES_DB: CookingBlog
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages         
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj*', '**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-    
    
      - name: Build API
        run: dotnet build CookingBlogBackend/PostApiService/PostApiService.csproj --configuration Debug

      - name: Start API in background
        env:
          ASPNETCORE_ENVIRONMENT: Testing
          JwtConfiguration__SecretKey: ${{ secrets.SecretKey }}          
          ASPNETCORE_URLS: "http://localhost:5189"
          ConnectionStrings__DefaultConnection: "Host=localhost;Port=5432;Database=CookingBlog;Username=postgres;Password=Password123!"
        run: |
          echo "Waiting for Postgres to warm up..."
          sleep 15                    
          dotnet run --project CookingBlogBackend/PostApiService/PostApiService.csproj --no-build > api.log 2>&1 &           
          sleep 20

      - name: Check API Status
        run: | 
          sleep 5        
          curl -i http://localhost:5189/api/posts || (echo "--- API LOGS ---" && cat api.log && exit 1)

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Tests
        run: |
          newman run postman/collection.json \
          -e postman/environment.json \
          --env-var "baseUrl=http://localhost:5189" \
          --reporters cli \          