name: CI Pipeline

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches: [dev]
  pull_request:
    branches: [main, dev]

jobs:
  validate:
    uses: ./.github/workflows/_tests.yml
    secrets:
      SecretKey: ${{ secrets.JWT_SECRET_KEY }}

  postman-validation:
    needs: validate    
    uses: ./.github/workflows/_postman_tests.yml
    secrets:
      SecretKey: ${{ secrets.JWT_SECRET_KEY }}

  deploy-staging:
    needs: postman-validation
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
    uses: ./.github/workflows/_deploy.yml
    with:
      environment: Staging
    secrets:
      RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}