name: CI Pipeline

on:
  push:
    branches: [dev]
  pull_request:
    branches: [main, dev]

jobs:
  validate:
    uses: ./.github/workflows/_tests.yml
    secrets:
      SecretKey: ${{ secrets.JWT_SECRET_KEY }}

  postman-validation:
    needs: validate
    uses: ./.github/workflows/_postman_tests.yml
    secrets:
      SecretKey: ${{ secrets.JWT_SECRET_KEY }}

  deploy-staging:
    needs: postman-validation
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
    environment: Staging
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy
        run: |
            curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}